apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    release: jupyter
spec:
  type: LoadBalancer
  publishNotReadyAddresses: false
  selector:
    release: jupyter
  ports:
  - name: http
    port: 8888
    protocol: TCP
#   - name: blockmanager
#     port: 7777
#     protocol: TCP
#   - name: driver
#     port: 2222
#     protocol: TCP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook-data
  labels:
    release: jupyter
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  storageClassName: csi-hostpath-sc
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-data-claim
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter
  labels:
    release: jupyter
spec:
  volumes:
    - name: notebook-data
      persistentVolumeClaim:
        claimName: notebook-data-claim
  containers:
    - name: jupyter
      image: jupyter/tensorflow-notebook
      ports:
        - name: http
          containerPort: 8888
          protocol: TCP
        # - name: blockmanager
        #   containerPort: 7777
        #   protocol: TCP
        # - name: driver
        #   containerPort: 2222
        #   protocol: TCP
      volumeMounts:
        - name: notebook-data
          mountPath: "/home/jovyan"
      resources:
        requests:
          memory: 1000Mi
        limits:
          cpu: 2
  initContainers:
      - name: jupyter-data-permission-fix
        image: busybox
        command: ["/bin/chmod","-R","777", "/data"]
        volumeMounts:
        - name: notebook-data
          mountPath: /data